# Generated by Django 2.1.5 on 2019-01-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_catcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='label',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='language',
            new_name='languages',
        ),
    ]
