# Generated by Django 2.1.5 on 2019-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_catcher', '0002_auto_20190117_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
