# Generated by Django 2.1.7 on 2019-02-16 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issue_catcher', '0004_githubrequestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrequestlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='githubrequestlog',
            name='success',
        ),
        migrations.AddField(
            model_name='githubrequestlog',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubrequestlog',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
