# Generated by Django 2.1.7 on 2019-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_catcher', '0006_auto_20190216_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrequestlog',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
